### PR TITLE
fix: missing await in fetchData function (server-side)

### PR DESCRIPTION
**Pull request by yawuxi**

### CODE REVIEW

**Comment by arorachakit** [comment]
Hey @yawuxi ! 
I am not sure if this would be needed because we have an await in the main function. 
Maybe I am missing any best approaches, do you mind sharing a bit more?

**Comment by yawuxi** [comment]
Hi @arorachakit!
Sure! Without await function will return promise, instead of promise with resulting data, also it affects on error handling. Without await you can't handle errors with try...catch in `fetchData()`, beacuse you returning promise and don't awaiting for result. Sure you still can use `.then` and `.catch`. But here we have `async` function and we dont need this handlers

Potentially someone can add extra code which transform our data for example. Without await we receiving promise instead of data

**Comment by arorachakit** [comment]
Hey @yawuxi ! 
That makes sense, I will merge this.
Would you also like to create a pull request for the main branch (with live editing enabled) ? 
Let me know what you think :)

**Comment by yawuxi** [comment]
@arorachakit Great! I'll create pull request, what you mean - "with live editing enabled"

**Comment by arorachakit** [comment]
@yawuxi - There are two branches in this repo, one for live editing enabled mode and other for server side mode. 
The PR you have created is in one of the branches. It would be great if you can create in both of them :)

**Comment by yawuxi** [comment]
@arorachakit uh, yep :) Created!

**Comment by arorachakit** [comment]
Awesome, thank you for your contribution.

**Pull request merged**
